name: go_app

services:
  psql:
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    image: postgres:16-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    container_name: psql
    networks:
      - net
  
  app:
    build: .
    environment:
      CONFIG_PATH: config/config.yaml
      PG_URL: postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      - psql
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    networks:
      - net
  
  integration:
    build:
      context: .
      dockerfile: integration_tests/Dockerfile
    depends_on:
      - app
    profiles:
      - tests
    networks:
      - net

volumes:
  pg-data:
    driver: local

networks:
  net:
    driver: bridge