version: "3.8"

name: go_app

services:
  # app:
  #   build: .
  #   environment:
  #     CONFIG_PATH: config/config.yaml
  #     PG_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./logs:/logs
  #   networks:
  #     - net

  psql:
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    image: postgres:16-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    container_name: psql
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - psql
    networks:
      - net
  
  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    # depends_on:
    #   - app
    profiles:
      - tests
    networks:
      - net

volumes:
  pg-data:
    driver: local

networks:
  net:
    driver: bridge